[
    {
        title: "Daily Prothom alo",
        img: "https://www.allbanglanewspaper.xyz/assets/prothom-alo.com.jpg",
        category: "banglaNewspapers",
        url: "prothom-alo.com",
    },
    {
        title: "Bangladesh Pratidin",
        img: "https://www.allbanglanewspaper.xyz/assets/bd-pratidin.com.jpg",
        category: "banglaNewspapers",
        url: "bd-pratidin.com",
    },
    {
        title: "Ittefaq",
        img: "https://www.allbanglanewspaper.xyz/assets/ittefaq.com.bd.jpg",
        category: "banglaNewspapers",
        url: "ittefaq.com.bd",
    },
    {
        title: "Daily kaler kantho",
        img: "https://www.allbanglanewspaper.xyz/assets/kalerkantho.com.jpg",
        category: "banglaNewspapers",
        url: "kalerkantho.com",
    },
    {
        title: "Daily Naya Diganta",
        img: "https://www.allbanglanewspaper.xyz/assets/dailynayadiganta.com.jpg",
        category: "banglaNewspapers",
        url: "dailynayadiganta.com",
    },
    {
        title: "Daily Amar Sangbad",
        img: "https://www.allbanglanewspaper.xyz/assets/amar-sangbad.com.jpg",
        category: "banglaNewspapers",
        url: "amar-sangbad.com",
    },
    {
        title: "Protidiner Sangbad",
        img: "https://www.allbanglanewspaper.xyz/assets/protidinersangbad.com.jpg",
        category: "banglaNewspapers",
        url: "protidinersangbad.com",
    },
    {
        title: "Jugantor",
        img: "https://www.allbanglanewspaper.xyz/assets/jugantor.com.jpg",
        category: "banglaNewspapers",
        url: "jugantor.com",
    },
    {
        title: "Daily Sangram",
        img: "https://www.allbanglanewspaper.xyz/assets/dailysangram.com.jpg",
        category: "banglaNewspapers",
        url: "dailysangram.com",
    },
    {
        title: "Daily Manab Zamin",
        img: "https://www.allbanglanewspaper.xyz/assets/mzamin.com.jpg",
        category: "banglaNewspapers",
        url: "mzamin.com",
    },
    {
        title: "Dainik Amadershomoy",
        img: "https://www.allbanglanewspaper.xyz/assets/dainikamadershomoy.com.jpg",
        category: "banglaNewspapers",
        url: "dainikamadershomoy.com",
    },
    {
        title: "Bonik Barta",
        img: "https://www.allbanglanewspaper.xyz/assets/bonikbarta.com.jpg",
        category: "banglaNewspapers",
        url: "bonikbarta.net",
    },
    {
        title: "Samakal",
        img: "https://www.allbanglanewspaper.xyz/assets/samakal.net.jpg",
        category: "banglaNewspapers",
        url: "samakal.net",
    },
    {
        title: "Janakantha",
        img: "https://www.allbanglanewspaper.xyz/assets/dailyjanakantha.com.jpg",
        category: "banglaNewspapers",
        url: "dailyjanakantha.com",
    },
    {
        title: "Jai Jai Din",
        img: "https://www.allbanglanewspaper.xyz/assets/jjdin.com.jpg",
        category: "banglaNewspapers",
        url: "jjdin.com",
    },
    {
        title: "Daily Bhorer Kagoj",
        img: "https://www.allbanglanewspaper.xyz/assets/bhorerkagoj.net.jpg",
        category: "banglaNewspapers",
        url: "bhorerkagoj.net",
    },
    {
        title: "Arthoniteer Kagoj",
        img: "https://www.allbanglanewspaper.xyz/assets/arthoniteerkagoj.com.jpg",
        category: "banglaNewspapers",
        url: "arthoniteerkagoj.com",
    },
    {
        title: "Daily Inqilab",
        img: "https://www.allbanglanewspaper.xyz/assets/the-daily-inqilab.png",
        category: "banglaNewspapers",
        url: "dailyinqilab.com",
    },
    {
        title: "Sangbad",
        img: "https://www.allbanglanewspaper.xyz/assets/sangbad.png",
        category: "banglaNewspapers",
        url: "thesangbad.net",
    },
    {
        title: "Manob Kantha",
        img: "https://www.allbanglanewspaper.xyz/assets/manobkantha.com.jpg",
        category: "banglaNewspapers",
        url: "manobkantha.com",
    },
    {
        title: "Daily Suprobhat",
        img: "https://www.allbanglanewspaper.xyz/assets/suprobhat.com.jpg",
        category: "banglaNewspapers",
        url: "suprobhat.com",
    },
    {
        title: "Bangladesh Journal",
        img: "https://www.allbanglanewspaper.xyz/assets/bdjournal.jpg",
        category: "banglaNewspapers",
        url: "bd-journal",
    },
    {
        title: "Daily Dinkal",
        img: "https://www.allbanglanewspaper.xyz/assets/dailydinkal.net.jpg",
        category: "banglaNewspapers",
        url: "dailydinkal.net",
    },
    {
        title: "Alokito Bangladesh",
        img: "https://www.allbanglanewspaper.xyz/assets/alokitobangladesh.com.jpg",
        category: "banglaNewspapers",
        url: "alokitobangladesh.com",
    },
    {
        title: "Ajker Bazar",
        img: "https://www.allbanglanewspaper.xyz/assets/ajkerbazzar.com.jpg",
        category: "banglaNewspapers",
        url: "ajkerbazzar.com",
    },
    {
        title: "Amadar Orthoneeti",
        img: "https://www.allbanglanewspaper.xyz/assets/daily-amadar-orthoneeti.png",
        category: "banglaNewspapers",
        url: "amaderorthoneeti.com",
    },
    {
        title: "Bangladesh Post",
        img: "https://www.allbanglanewspaper.xyz/assets/bangladeshpost.jpg",
        category: "banglaNewspapers",
        url: "bangladeshpost.net",
    },
    {
        title: "Sorejomin Barta",
        img: "https://www.allbanglanewspaper.xyz/assets/sorejominbarta.com.jpg",
        category: "banglaNewspapers",
        url: "sorejominbarta.com",
    },
    {
        title: "Khabar Patra",
        img: "https://www.allbanglanewspaper.xyz/assets/khabarpatrabd.com.jpg",
        category: "banglaNewspapers",
        url: "khabarpatrabd.com",
    },
    {
        title: "Vorer Pata",
        img: "https://www.allbanglanewspaper.xyz/assets/dailyvorerpata.com.jpg",
        category: "banglaNewspapers",
        url: "dailyvorerpata.com",
    },
    {
        title: "Shomoyer Alo",
        img: "https://www.allbanglanewspaper.xyz/assets/shomoyeralo.jpg",
        category: "banglaNewspapers",
        url: "shomoyeralo.com",
    },
    {
        title: "Kal Bela",
        img: "https://www.allbanglanewspaper.xyz/assets/kalbela.png",
        category: "banglaNewspapers",
        url: "kalbela.com",
    },
    {
        title: "Natun Barta",
        img: "https://www.allbanglanewspaper.xyz/assets/natun-barta.com.jpg",
        category: "banglaNewspapers",
        url: "natun-barta.com",
    },
    {
        title: "Share biz",
        img: "https://www.allbanglanewspaper.xyz/assets/sharebiz.net.jpg",
        category: "banglaNewspapers",
        url: "sharebiz.net",
    },
    {
        title: "Daily Bartoman",
        img: "https://www.allbanglanewspaper.xyz/assets/dailybartoman.com.jpg",
        category: "banglaNewspapers",
        url: "dailybartoman.com",
    },
    {
        title: "Ajkaler Khobor",
        img: "https://www.allbanglanewspaper.xyz/assets/ajkalerkhobor.com.jpg",
        category: "banglaNewspapers",
        url: "ajkalerkhobor.com",
    },
    {
        title: "Sangbad Konika",
        img: "https://www.allbanglanewspaper.xyz/assets/sangbadkonika.com.jpg",
        category: "banglaNewspapers",
        url: "sangbadkonika.com",
    },
    {
        title: "Khola Kagoj",
        img: "https://www.allbanglanewspaper.xyz/assets/kholakagojbd.com.gif",
        category: "banglaNewspapers",
        url: "kholakagojbd.com",
    },
    {
        title: "Gonokantho",
        img: "https://www.allbanglanewspaper.xyz/assets/gonokantho.jpg",
        category: "banglaNewspapers",
        url: "gonokantho.com",
    },
    {
        title: "Daily Star",
        img: "https://www.allbanglanewspaper.xyz/assets/thedailystar.net.jpg",
        category: "banglaNewspapers",
        url: "thedailystar.net",
    },
    {
        title: "Daily Observer",
        img: "https://www.allbanglanewspaper.xyz/assets/observerbd.com.jpg",
        category: "banglaNewspapers",
        url: "observerbd.com",
    },
    {
        title: "Financial Express",
        img: "https://www.allbanglanewspaper.xyz/assets/thefinancialexpress-bd.com.jpg",
        category: "banglaNewspapers",
        url: "thefinancialexpress.com.bd",
    },
    {
        title: "Desh Rupantor",
        img: "https://www.allbanglanewspaper.xyz/assets/deshrupantor.com.gif",
        category: "banglaNewspapers",
        url: "deshrupantor.com",
    },
    {
        title: "Bangladesher Khabor",
        img: "https://www.allbanglanewspaper.xyz/assets/bangladesher-khobor-logo.gif",
        category: "banglaNewspapers",
        url: "bangladesherkhabor.net",
    },
    {
        title: "Bd Bulletin",
        img: "https://www.allbanglanewspaper.xyz/assets/bd-bulletin.jpg",
        category: "banglaNewspapers",
        url: "bd-bulletin",
    },
    {
        title: "Daily Jagran",
        img: "https://www.allbanglanewspaper.xyz/assets/dailyjagaran.com.png",
        category: "banglaNewspapers",
        url: "dailyjagaran.com",
    },
    {
        title: "Business Standard",
        img: "https://www.allbanglanewspaper.xyz/assets/tbsnews.net.png",
        category: "banglaNewspapers",
        url: "the business standard",
    },
    {
        title: "Dhaka Tribune",
        img: "https://www.allbanglanewspaper.xyz/assets/dhakatribune.jpg",
        category: "banglaNewspapers",
        url: "dhakatribune",
    },
    {
        title: "Business Post",
        img: "https://www.allbanglanewspaper.xyz/assets/businesspostbd.com.jpg",
        category: "banglaNewspapers",
        url: "businesspostbd.com",
    },
    {
        title: "Ajker Patrika",
        img: "https://www.allbanglanewspaper.xyz/assets/ajkerpatrika.jpg",
        category: "banglaNewspapers",
        url: "ajkerpatrika",
    },
    {
        title: "Dainik Bangla",
        img: "https://www.allbanglanewspaper.xyz/assets/dainik-bangla.jpg",
        category: "banglaNewspapers",
        url: "dainik bangla",
    },
    {
        title: "E Prothom Alo",
        img: "https://www.allbanglanewspaper.xyz/assets/e-prothom-alo.png",
        category: "ebanglaNewspapers",
        url: "epaper.prothomalo.com",
    },
    {
        title: "E BD Pratidin",
        img: "https://www.allbanglanewspaper.xyz/assets/bd-pratidin.com.jpg",
        category: "ebanglaNewspapers",
        url: "e-bd-pratidin.com",
    },
    {
        title: "E Jugantor",
        img: "https://www.allbanglanewspaper.xyz/assets/epaper.jugantor.gif",
        category: "ebanglaNewspapers",
        url: "ejugantor.com",
    },
    {
        title: "E Samakal",
        img: "https://www.allbanglanewspaper.xyz/assets/e-samakal.png",
        category: "ebanglaNewspapers",
        url: "epaper.samakal.com",
    },
    {
        title: "E Janakantha",
        img: "https://www.allbanglanewspaper.xyz/assets/e-janakontho.png",
        category: "ebanglaNewspapers",
        url: "edailyjanakantha.com",
    },
    {
        title: "E Bonik Barta",
        img: "https://www.allbanglanewspaper.xyz/assets/ebonikbarta.net.gif",
        category: "ebanglaNewspapers",
        url: "epaper.bonikbarta.net",
    },
    {
        title: "E Naya Diganta",
        img: "https://www.allbanglanewspaper.xyz/assets/enayadiganta.com.gif",
        category: "ebanglaNewspapers",
        url: "enayadiganta.com",
    },
    {
        title: "E Financial Express",
        img: "https://www.allbanglanewspaper.xyz/assets/thefinancialexpress-bd.com.jpg",
        category: "ebanglaNewspapers",
        url: "epaper.thefinancialexpress.com.bd",
    },
    {
        title: "E Ittefaq",
        img: "https://www.allbanglanewspaper.xyz/assets/e-ittefaq.png",
        category: "ebanglaNewspapers",
        url: "epaper.ittefaq.com.bd",
    },
    {
        title: "E Kalerkantho",
        img: "https://www.allbanglanewspaper.xyz/assets/e-kalerkantho.png",
        category: "ebanglaNewspapers",
        url: "ekalerkantho.com",
    },
    {
        title: "E amadershomoy",
        img: "https://www.allbanglanewspaper.xyz/assets/e-amadershomoy.png",
        category: "ebanglaNewspapers",
        url: "epaper.dainikamadershomoy.com",
    },
    {
        title: "E Jai Jai Din",
        img: "https://www.allbanglanewspaper.xyz/assets/jjdin.com.jpg",
        category: "ebanglaNewspapers",
        url: "ejjdin.com",
    },
    {
        title: "E Daily Inqilab",
        img: "https://www.allbanglanewspaper.xyz/assets/the-daily-inqilab.png",
        category: "ebanglaNewspapers",
        url: "dailyinqilab epaper",
    },
    {
        title: "Daily Star Epaper",
        img: "https://www.allbanglanewspaper.xyz/assets/thedailystar.net.jpg",
        category: "ebanglaNewspapers",
        url: "dailystar epaper",
    },
    {
        title: "E Business Standard",
        img: "https://www.allbanglanewspaper.xyz/assets/tbsnews.net.png",
        category: "ebanglaNewspapers",
        url: "the business standard epaper",
    },
    {
        title: "E Share biz",
        img: "https://www.allbanglanewspaper.xyz/assets/esharebiz.jpg",
        category: "ebanglaNewspapers",
        url: "epaper sharebiz",
    },
    {
        title: "E Bhorer Kagoj",
        img: "https://www.allbanglanewspaper.xyz/assets/bhorer-kagoj-epaper.jpg",
        category: "ebanglaNewspapers",
        url: "bhorer kagoj epaper",
    },
    {
        title: "E Bangladesh Today",
        img: "https://www.allbanglanewspaper.xyz/assets/thebangladeshtoday.com.jpg",
        category: "ebanglaNewspapers",
        url: "e bangladesh today",
    },
    {
        title: "BD News 24",
        img: "https://www.allbanglanewspaper.xyz/assets/bangla.bdnews24.com.jpg",
        category: "onlineNewspaper",
        url: "bangla.bdnews24.com",
    },
    {
        title: "Bangla News 24",
        img: "https://www.allbanglanewspaper.xyz/assets/banglanews24.com.jpg",
        category: "onlineNewspaper",
        url: "banglanews24.com",
    },
    {
        title: "Jago News 24",
        img: "https://www.allbanglanewspaper.xyz/assets/jagonews24.com.jpg",
        category: "onlineNewspaper",
        url: "jagonews24.com",
    },
    {
        title: "Priyo",
        img: "https://www.allbanglanewspaper.xyz/assets/priyo.com.png",
        category: "onlineNewspaper",
        url: "priyo.com",
    },
    {
        title: "Amadershomoy",
        img: "https://www.allbanglanewspaper.xyz/assets/amadershomoys.com.jpg",
        category: "onlineNewspaper",
        url: "amadershomoys.com",
    },
    {
        title: "Bd24live",
        img: "https://www.allbanglanewspaper.xyz/assets/bd24live.com.jpg",
        category: "onlineNewspaper",
        url: "bd24live.com",
    },
    {
        title: "Risingbd",
        img: "https://www.allbanglanewspaper.xyz/assets/risingbd.com.jpg",
        category: "onlineNewspaper",
        url: "risingbd.com",
    },
    {
        title: "Daily Bangladesh",
        img: "https://www.allbanglanewspaper.xyz/assets/daily-bangladesh.png",
        category: "onlineNewspaper",
        url: "daily-bangladesh.com",
    },
    {
        title: "Gonews 24",
        img: "https://www.allbanglanewspaper.xyz/assets/gonews24.com.jpg",
        category: "onlineNewspaper",
        url: "gonews24.com",
    },
    {
        title: "Dhaka Post",
        img: "https://www.allbanglanewspaper.xyz/assets/dhaka-post.jpg",
        category: "onlineNewspaper",
        url: "dhakapost.com",
    },
    {
        title: "Bangla Tribune",
        img: "https://www.allbanglanewspaper.xyz/assets/banglatribune.com.jpg",
        category: "onlineNewspaper",
        url: "banglatribune.com",
    },
    {
        title: "Bangla Insider",
        img: "https://www.allbanglanewspaper.xyz/assets/bangla-insider.jpg",
        category: "onlineNewspaper",
        url: "banglainsider.com",
    },
    {
        title: "UNB",
        img: "https://www.allbanglanewspaper.xyz/assets/unb.jpg",
        category: "onlineNewspaper",
        url: "unb.com.bd",
    },
    {
        title: "BSS News",
        img: "https://www.allbanglanewspaper.xyz/assets/bssnews.net.jpg",
        category: "onlineNewspaper",
        url: "bssnews.net",
    },
    {
        title: "Barta24",
        img: "https://www.allbanglanewspaper.xyz/assets/barta24.com.jpg",
        category: "onlineNewspaper",
        url: "barta24.com",
    },
    {
        title: "Amar Desh",
        img: "https://www.allbanglanewspaper.xyz/assets/amardesh-24.png",
        category: "onlineNewspaper",
        url: "আমার দেশ",
    },
    {
        title: "Sarabangla",
        img: "https://www.allbanglanewspaper.xyz/assets/sarabangla.webp",
        category: "onlineNewspaper",
        url: "sarabangla.net",
    },
    {
        title: "Breaking News",
        img: "https://www.allbanglanewspaper.xyz/assets/breakingnews.jpg",
        category: "onlineNewspaper",
        url: "breakingnews.com.bd",
    },
    {
        title: "Dhaka Times",
        img: "https://www.allbanglanewspaper.xyz/assets/dhakatimes.com.bd.jpg",
        category: "onlineNewspaper",
        url: "dhakatimes.com.bd",
    },
    {
        title: "DMP News",
        img: "https://www.allbanglanewspaper.xyz/assets/dmpnews.png",
        category: "onlineNewspaper",
        url: "dmpnews.org",
    },
    {
        title: "Natun Barta",
        img: "https://www.allbanglanewspaper.xyz/assets/natunbarta.com.jpg",
        category: "onlineNewspaper",
        url: "natunbarta.com",
    },
    {
        title: "The Report 24",
        img: "https://www.allbanglanewspaper.xyz/assets/thereport24.com.png",
        category: "onlineNewspaper",
        url: "thereport24.com",
    },
    {
        title: "Somoyer Konthosor",
        img: "https://www.allbanglanewspaper.xyz/assets/somoyerkonthosor.com.jpg",
        category: "onlineNewspaper",
        url: "somoyerkonthosor.com",
    },
    {
        title: "Bangla Telegraph",
        img: "https://www.allbanglanewspaper.xyz/assets/banglatelegraph.gif",
        category: "onlineNewspaper",
        url: "banglatelegraph.com",
    },
    {
        title: "Bdview24",
        img: "https://www.allbanglanewspaper.xyz/assets/bdview24.com.jpg",
        category: "onlineNewspaper",
        url: "bdview24.com",
    },
    {
        title: "Bd Journal365",
        img: "https://www.allbanglanewspaper.xyz/assets/bdjournal365.com.jpg",
        category: "onlineNewspaper",
        url: "bdjournal365.com",
    },
    {
        title: "Artho Suchak",
        img: "https://www.allbanglanewspaper.xyz/assets/arthosuchak.com.jpg",
        category: "onlineNewspaper",
        url: "arthosuchak.com",
    },
    {
        title: "Share News 24",
        img: "https://www.allbanglanewspaper.xyz/assets/sharenews24.com.jpg",
        category: "onlineNewspaper",
        url: "sharenews24.com",
    },
    {
        title: "Sunbd24",
        img: "https://www.allbanglanewspaper.xyz/assets/sunbd24.png",
        category: "onlineNewspaper",
        url: "sunbd24.com",
    },
    {
        title: "Orthosongbad",
        img: "https://www.allbanglanewspaper.xyz/assets/orthosongbad.jpg",
        category: "onlineNewspaper",
        url: "orthosongbad.com",
    },
    {
        title: "Poriborton",
        img: "https://www.allbanglanewspaper.xyz/assets/poriborton.com.jpg",
        category: "onlineNewspaper",
        url: "poriborton.com",
    },
    {
        title: "Nagorik Kantha",
        img: "https://www.allbanglanewspaper.xyz/assets/nagorikkantha.com.jpg",
        category: "onlineNewspaper",
        url: "nagorikkantha.com",
    },
    {
        title: "Media Khabor",
        img: "https://www.allbanglanewspaper.xyz/assets/mediakhabor.com.jpg",
        category: "onlineNewspaper",
        url: "mediakhabor.com",
    },
    {
        title: "Sotta Sangbad",
        img: "https://www.allbanglanewspaper.xyz/assets/ajkersottasangbad24.com.jpg",
        category: "onlineNewspaper",
        url: "ajkersottasangbad24.com",
    },
    {
        title: "Dhaka Post",
        img: "https://www.allbanglanewspaper.xyz/assets/thedhakapost.com.jpg",
        category: "onlineNewspaper",
        url: "thedhakapost.com",
    },
    {
        title: "1News BD",
        img: "https://www.allbanglanewspaper.xyz/assets/1newsbd.com.jpg",
        category: "onlineNewspaper",
        url: "1newsbd.com",
    },
    {
        title: "Aparadh Chokh",
        img: "https://www.allbanglanewspaper.xyz/assets/aparadhchokh24bd.com.jpg",
        category: "onlineNewspaper",
        url: "aparadhchokh24bd.com",
    },
    {
        title: "Times World",
        img: "https://www.allbanglanewspaper.xyz/assets/timesworld24.com.jpg",
        category: "onlineNewspaper",
        url: "timesworld24.com",
    },
    {
        title: "Desh News",
        img: "https://www.allbanglanewspaper.xyz/assets/deshnews.net.jpg",
        category: "onlineNewspaper",
        url: "deshnews.net",
    },
    {
        title: "RTNN",
        img: "https://www.allbanglanewspaper.xyz/assets/rtnn.net.jpg",
        category: "onlineNewspaper",
        url: "rtnn.net",
    },
    {
        title: "Desher Sangbad",
        img: "https://www.allbanglanewspaper.xyz/assets/deshersangbad.com.jpg",
        category: "onlineNewspaper",
        url: "deshersangbad.com",
    },
    {
        title: "Last News Bd",
        img: "https://www.allbanglanewspaper.xyz/assets/lastnewsbd.com.jpg",
        category: "onlineNewspaper",
        url: "lastnewsbd.com",
    },
    {
        title: "Bangla Daily 24",
        img: "https://www.allbanglanewspaper.xyz/assets/bangladaily24.com.jpg",
        category: "onlineNewspaper",
        url: "bangladaily24.com",
    },
    {
        title: "Protikhon",
        img: "https://www.allbanglanewspaper.xyz/assets/protikhon.com.jpg",
        category: "onlineNewspaper",
        url: "protikhon.com",
    },
    {
        title: "Prime News",
        img: "https://www.allbanglanewspaper.xyz/assets/primenewsbd.com.jpg",
        category: "onlineNewspaper",
        url: "primenewsbd.com",
    },
    {
        title: "MTNews",
        img: "https://www.allbanglanewspaper.xyz/assets/mtnews24.com.jpg",
        category: "onlineNewspaper",
        url: "mtnews24.com",
    },
    {
        title: "Deshe Bideshe",
        img: "https://www.allbanglanewspaper.xyz/assets/deshebideshe.com.jpg",
        category: "onlineNewspaper",
        url: "deshebideshe.com",
    },
    {
        title: "Boichitra News",
        img: "https://www.allbanglanewspaper.xyz/assets/boichitranews24.com.jpg",
        category: "onlineNewspaper",
        url: "boichitranews24.com",
    },
    {
        title: "Barta Bangla",
        img: "https://www.allbanglanewspaper.xyz/assets/bartabangla.com.jpg",
        category: "onlineNewspaper",
        url: "bartabangla.com",
    },
    {
        title: "Sangbad Protidin",
        img: "https://www.allbanglanewspaper.xyz/assets/sangbadprotidin24.com.jpg",
        category: "onlineNewspaper",
        url: "sangbadprotidin24.com",
    },
    {
        title: "BD Type",
        img: "https://www.allbanglanewspaper.xyz/assets/bdtype.com.jpg",
        category: "onlineNewspaper",
        url: "bdtype.com",
    },
    {
        title: "Zoom Bangla",
        img: "https://www.allbanglanewspaper.xyz/assets/news.zoombangla.com.jpg",
        category: "onlineNewspaper",
        url: "news.zoombangla.com",
    },
    {
        title: "Sheersha Sangbad",
        img: "https://www.allbanglanewspaper.xyz/assets/sheershasangbad.com.jpg",
        category: "onlineNewspaper",
        url: "sheershasangbad.com",
    },
    {
        title: "SNN24",
        img: "https://www.allbanglanewspaper.xyz/assets/snn24.com.jpg",
        category: "onlineNewspaper",
        url: "snn24.com",
    },
    {
        title: "Alert News",
        img: "https://www.allbanglanewspaper.xyz/assets/alertnews24.com.jpg",
        category: "onlineNewspaper",
        url: "alertnews24.com",
    },
    {
        title: "Crime Reporter",
        img: "https://www.allbanglanewspaper.xyz/assets/crimereporter24.com.jpg",
        category: "onlineNewspaper",
        url: "crimereporter24.com",
    },
    {
        title: "Khobor Protidin",
        img: "https://www.allbanglanewspaper.xyz/assets/khoborprotidin24.com.jpg",
        category: "onlineNewspaper",
        url: "khoborprotidin24.com",
    },
    {
        title: "BD Cricteam",
        img: "https://www.allbanglanewspaper.xyz/assets/bdcricteam.com.jpg",
        category: "onlineNewspaper",
        url: "bdcricteam.com",
    },
    {
        title: "Shersha News",
        img: "https://www.allbanglanewspaper.xyz/assets/shershanews24.com.png",
        category: "onlineNewspaper",
        url: "shershanews24.com",
    },
    {
        title: "Bbc 24 News",
        img: "https://www.allbanglanewspaper.xyz/assets/bbc24news.com.jpg",
        category: "onlineNewspaper",
        url: "bbc24news.com",
    },
    {
        title: "Tulpar24",
        img: "https://www.allbanglanewspaper.xyz/assets/tulpar24.com.jpg",
        category: "onlineNewspaper",
        url: "tulpar24.com",
    },
    {
        title: "Bangla Kagoj24",
        img: "https://www.allbanglanewspaper.xyz/assets/banglakagoj24.com.jpg",
        category: "onlineNewspaper",
        url: "banglakagoj24.com",
    },
    {
        title: "Latest bd news",
        img: "https://www.allbanglanewspaper.xyz/assets/latestbdnews.com.jpg",
        category: "onlineNewspaper",
        url: "latestbdnews.com",
    },
    {
        title: "Barta Bazar",
        img: "https://www.allbanglanewspaper.xyz/assets/bartabazar.com.jpg",
        category: "onlineNewspaper",
        url: "bartabazar.com",
    },
    {
        title: "Dhaka Protidin",
        img: "https://www.allbanglanewspaper.xyz/assets/dhakaprotidin.com.jpg",
        category: "onlineNewspaper",
        url: "dhakaprotidin.com",
    },
    {
        title: "Eibela",
        img: "https://www.allbanglanewspaper.xyz/assets/eibela.com.jpg",
        category: "onlineNewspaper",
        url: "eibela.com",
    },
    {
        title: "Sada Kalo",
        img: "https://www.allbanglanewspaper.xyz/assets/sadakalo24.com.jpg",
        category: "onlineNewspaper",
        url: "sadakalo24.com",
    },
    {
        title: "PBD",
        img: "https://www.allbanglanewspaper.xyz/assets/purbo-poshchim-bd.png",
        category: "onlineNewspaper",
        url: "pbd.news",
    },
    {
        title: "Techshohor",
        img: "https://www.allbanglanewspaper.xyz/assets/techshohor.jpg",
        category: "onlineNewspaper",
        url: "techshohor.com",
    },
    {
        title: "Tech Zoom",
        img: "https://www.allbanglanewspaper.xyz/assets/techzoom.jpg",
        category: "onlineNewspaper",
        url: "techzoom.tv",
    },
    {
        title: "Channel I",
        img: "https://www.allbanglanewspaper.xyz/assets/channel-i-tv.com.jpg",
        category: "tvchannels",
        url: "channel-i-tv.com",
    },
    {
        title: "Independent Tv",
        img: "https://www.allbanglanewspaper.xyz/assets/independent24.com.jpg",
        category: "tvchannels",
        url: "independent24.com",
    },
    {
        title: "Somoy News",
        img: "https://www.allbanglanewspaper.xyz/assets/somoynews.tv.jpg",
        category: "tvchannels",
        url: "somoynews.tv",
    },
    {
        title: "NTV BD",
        img: "https://www.allbanglanewspaper.xyz/assets/ntvbd.com.jpg",
        category: "tvchannels",
        url: "ntvbd.tv",
    },
    {
        title: "Channel 24 BD",
        img: "https://www.allbanglanewspaper.xyz/assets/channel24bd.tv.jpg",
        category: "tvchannels",
        url: "channel24bd.tv",
    },
    {
        title: "RTV",
        img: "https://www.allbanglanewspaper.xyz/assets/rtvonline.com.jpg",
        category: "tvchannels",
        url: "rtvonline.com",
    },
    {
        title: "Ekushey TV",
        img: "https://www.allbanglanewspaper.xyz/assets/ekushey-tv.com.jpg",
        category: "tvchannels",
        url: "ekushey-tv.com",
    },
    {
        title: "ATN Bangla",
        img: "https://www.allbanglanewspaper.xyz/assets/atnbangla.tv.jpg",
        category: "tvchannels",
        url: "atnbangla.tv",
    },
    {
        title: "Jamuna TV",
        img: "https://www.allbanglanewspaper.xyz/assets/jamunatelevision.com.jpg",
        category: "tvchannels",
        url: "jamunatelevision.com",
    },
    {
        title: "SATV",
        img: "https://www.allbanglanewspaper.xyz/assets/satv.tv.jpg",
        category: "tvchannels",
        url: "satv.tv",
    },
    {
        title: "Desh TV",
        img: "https://www.allbanglanewspaper.xyz/assets/desh.tv.jpg",
        category: "tvchannels",
        url: "desh.tv",
    },
    {
        title: "Maasranga TV",
        img: "https://www.allbanglanewspaper.xyz/assets/maasranga.tv.jpg",
        category: "tvchannels",
        url: "maasranga.tv",
    },
    {
        title: "Bangla Vision",
        img: "https://www.allbanglanewspaper.xyz/assets/banglavision.tv.jpg",
        category: "tvchannels",
        url: "banglavision.tv",
    },
    {
        title: "Ekattor TV",
        img: "https://www.allbanglanewspaper.xyz/assets/ekattor.tv.jpg",
        category: "tvchannels",
        url: "ekattor.tv",
    },
    {
        title: "ATN News",
        img: "https://www.allbanglanewspaper.xyz/assets/atnnewstv.com.jpg",
        category: "tvchannels",
        url: "atnnewstv.com",
    },
    {
        title: "Channel9 BD",
        img: "https://www.allbanglanewspaper.xyz/assets/channelninebd.tv.jpg",
        category: "tvchannels",
        url: "channelninebd.tv",
    },
    {
        title: "My TV",
        img: "https://www.allbanglanewspaper.xyz/assets/mytvbd.tv.jpg",
        category: "tvchannels",
        url: "mytvbd.tv",
    },
    {
        title: "Boishakhi TV",
        img: "https://www.allbanglanewspaper.xyz/assets/boishakhi.tv.jpg",
        category: "tvchannels",
        url: "boishakhi.tv",
    },
    {
        title: "Mohona TV",
        img: "https://www.allbanglanewspaper.xyz/assets/mohonatv.com.jpg",
        category: "tvchannels",
        url: "mohonatv.com",
    },
    {
        title: "Gazi TV (GTV)",
        img: "https://www.allbanglanewspaper.xyz/assets/gazitv.com.jpg",
        category: "tvchannels",
        url: "gazitv.com",
    },
    {
        title: "BTV",
        img: "https://www.allbanglanewspaper.xyz/assets/btv.gov.bd.jpg",
        category: "tvchannels",
        url: "btv.gov.bd",
    },
    {
        title: "Channel 16",
        img: "https://www.allbanglanewspaper.xyz/assets/channel-16tv.com.jpg",
        category: "tvchannels",
        url: "channel-16tv.com",
    },
    {
        title: "Gaan Bangla",
        img: "https://www.allbanglanewspaper.xyz/assets/gaanbangla.tv.jpg",
        category: "tvchannels",
        url: "gaanbangla.tv",
    },
    {
        title: "Asian TV",
        img: "https://www.allbanglanewspaper.xyz/assets/asiantvbd.com.jpg",
        category: "tvchannels",
        url: "asiantv.com.bd",
    },
    {
        title: "Daily Azadi",
        img: "https://www.allbanglanewspaper.xyz/assets/dainikazadi.org.png",
        category: "localCtgOnline",
        url: "dainikazadi.net",
    },
    {
        title: "Dainik Purbokone",
        img: "https://www.allbanglanewspaper.xyz/assets/dainikpurbokone.net.png",
        category: "localCtgOnline",
        url: "dainikpurbokone.net",
    },
    {
        title: "Daily Shangu",
        img: "https://www.allbanglanewspaper.xyz/assets/thedailyshangu.jpg",
        category: "localCtgOnline",
        url: "thedailyshangu.com",
    },
    {
        title: "Daily Purbo Desh",
        img: "https://www.allbanglanewspaper.xyz/assets/purbodesh.gif",
        category: "localCtgOnline",
        url: "dailypurbodesh.com",
    },
    {
        title: "Rupashi Bangla",
        img: "https://www.allbanglanewspaper.xyz/assets/dailyrupashibangla.jpg",
        category: "localCtgOnline",
        url: "dailyrupashibangla.com",
    },
    {
        title: "Suprobhat",
        img: "https://www.allbanglanewspaper.xyz/assets/suprobhat.jpg",
        category: "localCtgOnline",
        url: "suprobhat.com",
    },
    {
        title: "Ctg Times",
        img: "https://www.allbanglanewspaper.xyz/assets/ctgtimes.gif",
        category: "localCtgOnline",
        url: "ctgtimes.com",
    },
    {
        title: "CTN 24",
        img: "https://www.allbanglanewspaper.xyz/assets/ctn24.jpg",
        category: "localCtgOnline",
        url: "ctn24.com",
    },
    {
        title: "Parbatta News",
        img: "https://www.allbanglanewspaper.xyz/assets/parbattanews.gif",
        category: "localCtgOnline",
        url: "parbattanews.com",
    },
    {
        title: "Ctg Pratidin",
        img: "https://www.allbanglanewspaper.xyz/assets/ctgpratidin.jpg",
        category: "localCtgOnline",
        url: "ctgpratidin.com",
    },
    {
        title: "Cht Times 24",
        img: "https://www.allbanglanewspaper.xyz/assets/chttimes24.jpg",
        category: "localCtgOnline",
        url: "chttimes24.com",
    },
    {
        title: "Ctnews",
        img: "https://www.allbanglanewspaper.xyz/assets/ctnewsbd.jpg",
        category: "localCtgOnline",
        url: "ctnewsbd.com",
    },
    {
        title: "Khagrachari News",
        img: "https://www.allbanglanewspaper.xyz/assets/khagracharinews.jpg",
        category: "localCtgOnline",
        url: "khagracharinews.com",
    },
    {
        title: "Raozan News",
        img: "https://www.allbanglanewspaper.xyz/assets/raozannews.jpg",
        category: "localCtgOnline",
        url: "raozannews.com.bd",
    },
    {
        title: "Chattagram News",
        img: "https://www.allbanglanewspaper.xyz/assets/chattagramnews.com.jpg",
        category: "localCtgOnline",
        url: "chattagramnews.com",
    },
    {
        title: "Pahar 24",
        img: "https://www.allbanglanewspaper.xyz/assets/pahar24.jpg",
        category: "localCtgOnline",
        url: "pahar24.com",
    },
    {
        title: "Chatga Portal",
        img: "https://www.allbanglanewspaper.xyz/assets/chatgaportal.jpg",
        category: "localCtgOnline",
        url: "chatgaportal.com",
    },
    {
        title: "Chattogram Daily",
        img: "https://www.allbanglanewspaper.xyz/assets/chattogramdaily.jpg",
        category: "localCtgOnline",
        url: "chattogramdaily.com",
    },
    {
        title: "E Dainikpurbokone",
        img: "https://www.allbanglanewspaper.xyz/assets/edainikpurbokone.jpg",
        category: "localCtgCoxEOnline",
        url: "edainikpurbokone.net",
    },
    {
        title: "E Azadi",
        img: "https://www.allbanglanewspaper.xyz/assets/edainikazadi.jpg",
        category: "localCtgCoxEOnline",
        url: "edainikazadi.net",
    },
    {
        title: "E Suprobhat",
        img: "https://www.allbanglanewspaper.xyz/assets/esuprobhat.jpg",
        category: "localCtgCoxEOnline",
        url: "esuprobhat.com",
    },
    {
        title: "E Purbodesh",
        img: "https://www.allbanglanewspaper.xyz/assets/epurbodesh.jpg",
        category: "localCtgCoxEOnline",
        url: "epurbodesh.com",
    },
    {
        title: "Coxsbazar News",
        img: "https://www.allbanglanewspaper.xyz/assets/coxsbazarnews.gif",
        category: "localCoxOnline",
        url: "coxsbazarnews.com",
    },
    {
        title: "Dainik Coxsbazar",
        img: "https://www.allbanglanewspaper.xyz/assets/dainikcoxsbazar.png",
        category: "localCoxOnline",
        url: "dainikcoxsbazar.com",
    },
    {
        title: "Ajker Desh Bidesh",
        img: "https://www.allbanglanewspaper.xyz/assets/ajkerdeshbidesh.jpg",
        category: "localCoxOnline",
        url: "ajkerdeshbidesh.com",
    },
    {
        title: "Coxsbazar Journal",
        img: "https://www.allbanglanewspaper.xyz/assets/coxsbazarjournal.jpg",
        category: "localCoxOnline",
        url: "coxsbazarjournal.com",
    },
    {
        title: "Cox Bangla",
        img: "https://www.allbanglanewspaper.xyz/assets/coxbangla.jpg",
        category: "localCoxOnline",
        url: "coxbangla.com",
    },
    {
        title: "Coxsbazar Khobor",
        img: "https://www.allbanglanewspaper.xyz/assets/coxsbazarkhobor.jpg",
        category: "localCoxOnline",
        url: "coxsbazarkhobor.com",
    },
    {
        title: "Daily Coxsbazar",
        img: "https://www.allbanglanewspaper.xyz/assets/dailycoxsbazar.jpg",
        category: "localCoxOnline",
        url: "dailycoxsbazar.com",
    },
    {
        title: "Chakaria News",
        img: "https://www.allbanglanewspaper.xyz/assets/chakarianews.com.png",
        category: "localCoxOnline",
        url: "chakarianews.com",
    },
    {
        title: "Ukhiya News",
        img: "https://www.allbanglanewspaper.xyz/assets/ukhiyanews.com.jpg",
        category: "localCoxOnline",
        url: "ukhiyanews.com",
    },
    {
        title: "Teknaf News",
        img: "https://www.allbanglanewspaper.xyz/assets/teknafnews.jpg",
        category: "localCoxOnline",
        url: "teknafnews.com",
    },
    {
        title: "Saintmartin News",
        img: "https://www.allbanglanewspaper.xyz/assets/saintmartinbdnews.jpg",
        category: "localCoxOnline",
        url: "saintmartinbdnews.com",
    },
    {
        title: "Amader Ramu",
        img: "https://www.allbanglanewspaper.xyz/assets/amaderramu.jpg",
        category: "localCoxOnline",
        url: "amaderramu.com",
    },
    {
        title: "Sylhet View 24",
        img: "https://www.allbanglanewspaper.xyz/assets/sylhetview24.gif",
        category: "localSylhet",
        url: "sylhetview24.net",
    },
    {
        title: "Daily Sylhet",
        img: "https://www.allbanglanewspaper.xyz/assets/dailysylhet.gif",
        category: "localSylhet",
        url: "dailysylhet.com",
    },
    {
        title: "Khowai",
        img: "https://www.allbanglanewspaper.xyz/assets/dailykhowai.com.jpg",
        category: "localSylhet",
        url: "dailykhowai.com",
    },
    {
        title: "Sylheter Sokal",
        img: "https://www.allbanglanewspaper.xyz/assets/sylhetersokal.gif",
        category: "localSylhet",
        url: "sylhetersokal.com",
    },
    {
        title: "Sylheter Dak",
        img: "https://www.allbanglanewspaper.xyz/assets/sylheterdak.gif",
        category: "localSylhet",
        url: "sylheterdak.com.bd",
    },
    {
        title: "Amader Sylhet",
        img: "https://www.allbanglanewspaper.xyz/assets/amadersylhet.gif",
        category: "localSylhet",
        url: "amadersylhet.com",
    },
    {
        title: "Purbanchal",
        img: "https://www.allbanglanewspaper.xyz/assets/purbanchal.com.png",
        category: "localKhulna",
        url: "purbanchal.com",
    },
    {
        title: "Khulna News",
        img: "https://www.allbanglanewspaper.xyz/assets/khulnanews.com.png",
        category: "localKhulna",
        url: "khulnanews.com",
    },
    {
        title: "Khulnanchal",
        img: "https://www.allbanglanewspaper.xyz/assets/daily-khulnanchal.png",
        category: "localKhulna",
        url: "khulnanchal.com",
    },
    {
        title: "Daily Gramerkagoj",
        img: "https://www.allbanglanewspaper.xyz/assets/gramer-kagoj.png",
        category: "localKhulna",
        url: "gramerkagoj.com",
    },
    {
        title: "Satkhira News",
        img: "https://www.allbanglanewspaper.xyz/assets/satkhiranews.jpg",
        category: "localKhulna",
        url: "satkhiranews.com",
    },
    {
        title: "Daily Probaha",
        img: "https://www.allbanglanewspaper.xyz/assets/daily-prabaha.jpg",
        category: "localKhulna",
        url: "dailyprobaha.com.bd",
    },
    {
        title: "Amader Barisal",
        img: "https://www.allbanglanewspaper.xyz/assets/amaderbarisal.com.jpg",
        category: "localBarisal",
        url: "amaderbarisal.com",
    },
    {
        title: "Barisal News",
        img: "https://www.allbanglanewspaper.xyz/assets/barisalnews.com.jpg",
        category: "localBarisal",
        url: "barisalnews.com",
    },
    {
        title: "Ajkerbarta",
        img: "https://www.allbanglanewspaper.xyz/assets/ajker-barta.webp",
        category: "localBarisal",
        url: "ajkerbarta.com",
    },
    {
        title: "Barisal Today",
        img: "https://www.allbanglanewspaper.xyz/assets/barisal-today.webp",
        category: "localBarisal",
        url: "barisaltoday.com",
    },
    {
        title: "Matobad",
        img: "https://www.allbanglanewspaper.xyz/assets/matobad.webp",
        category: "localBarisal",
        url: "dailymatobad.com",
    },
    {
        title: "Ajker Paribartan",
        img: "https://www.allbanglanewspaper.xyz/assets/ajkerparibartan.webp",
        category: "localBarisal",
        url: "ajkerparibartan.com",
    },
    {
        title: "Barishal Times",
        img: "https://www.allbanglanewspaper.xyz/assets/barisaltimes.webp",
        category: "localBarisal",
        url: "barishaltimes.com",
    },
    {
        title: "Amar Barishal 24",
        img: "https://www.allbanglanewspaper.xyz/assets/amarbarisal24.webp",
        category: "localBarisal",
        url: "amarbarishal24.com",
    },
    {
        title: "Bhola News",
        img: "https://www.allbanglanewspaper.xyz/assets/bholanews.webp",
        category: "localBarisal",
        url: "bholanews.com",
    },
    {
        title: "Kuakata News",
        img: "https://www.allbanglanewspaper.xyz/assets/kuakatanews.webp",
        category: "localBarisal",
        url: "kuakatanews.com",
    },
    {
        title: "Chandpur Kantho",
        img: "https://www.allbanglanewspaper.xyz/assets/chandpur-kantho.webp",
        category: "localBarisal",
        url: "chandpur-kantho.com",
    },
    {
        title: "Ajker Bhola",
        img: "https://www.allbanglanewspaper.xyz/assets/ajkerbhola.webp",
        category: "localBarisal",
        url: "ajkerbhola.com",
    },
    {
        title: "Bholar Bani",
        img: "https://www.allbanglanewspaper.xyz/assets/bholarbani.webp",
        category: "localBarisal",
        url: "bholarbani.com",
    },
    {
        title: "Amader Comilla",
        img: "https://www.allbanglanewspaper.xyz/assets/dailyamadercomilla.com.png",
        category: "otherLocalNewspapers",
        url: "dailyamadercomilla.com",
    },
    {
        title: "Matha Bhanga",
        img: "https://www.allbanglanewspaper.xyz/assets/mathabhanga.com.png",
        category: "otherLocalNewspapers",
        url: "mathabhanga.com",
    },
    {
        title: "Rajshahi News 24",
        img: "https://www.allbanglanewspaper.xyz/assets/rajshahinews24.com.png",
        category: "otherLocalNewspapers",
        url: "rajshahinews24.com",
    },
    {
        title: "Daily Karatoa",
        img: "https://www.allbanglanewspaper.xyz/assets/karatoa.com.bd.jpg",
        category: "otherLocalNewspapers",
        url: "karatoa.com.bd",
    },
    {
        title: "Dainik Sylhet",
        img: "https://www.allbanglanewspaper.xyz/assets/dainiksylhet.com.jpg",
        category: "otherLocalNewspapers",
        url: "dainiksylhet.com",
    },
    {
        title: "Uttorpurbo",
        img: "https://www.allbanglanewspaper.xyz/assets/uttorpurbo.com.jpg",
        category: "otherLocalNewspapers",
        url: "uttorpurbo.com",
    },
    {
        title: "Ajker Jamalpur",
        img: "https://www.allbanglanewspaper.xyz/assets/ajkerjamalpur.com.jpg",
        category: "otherLocalNewspapers",
        url: "ajkerjamalpur.com",
    },
    {
        title: "Surma Times",
        img: "https://www.allbanglanewspaper.xyz/assets/surmatimes.com.jpg",
        category: "otherLocalNewspapers",
        url: "surmatimes.com",
    },
    {
        title: "Dinajpur News",
        img: "https://www.allbanglanewspaper.xyz/assets/dinajpurnews.com.png",
        category: "otherLocalNewspapers",
        url: "dinajpurnews.com",
    },
    {
        title: "Chadpur Times",
        img: "https://www.allbanglanewspaper.xyz/assets/chandpurtimes.com.jpg",
        category: "otherLocalNewspapers",
        url: "chandpurtimes.com",
    },
    {
        title: "Mukto Khobor 24",
        img: "https://www.allbanglanewspaper.xyz/assets/muktokhobor24.com.jpg",
        category: "otherLocalNewspapers",
        url: "muktokhobor24.com",
    },
    {
        title: "Bogra Sangbad",
        img: "https://www.allbanglanewspaper.xyz/assets/bograsangbad.com.jpg",
        category: "otherLocalNewspapers",
        url: "bograsangbad.com",
    },
    {
        title: "Rajshahir Somoy",
        img: "https://www.allbanglanewspaper.xyz/assets/rajshahirsomoy.com.jpg",
        category: "otherLocalNewspapers",
        url: "rajshahirsomoy.com",
    },
    {
        title: "Chandpurweb",
        img: "https://www.allbanglanewspaper.xyz/assets/chandpurweb.com.jpg",
        category: "otherLocalNewspapers",
        url: "chandpurweb.com",
    },
    {
        title: "Sylhet Express",
        img: "https://www.allbanglanewspaper.xyz/assets/sylhetexpress.com.jpg",
        category: "otherLocalNewspapers",
        url: "sylhetexpress.com",
    },
    {
        title: "Laksmipur 24",
        img: "https://www.allbanglanewspaper.xyz/assets/lakshmipur24.com.jpg",
        category: "otherLocalNewspapers",
        url: "lakshmipur24.com",
    },
    {
        title: "Prothom Feni",
        img: "https://www.allbanglanewspaper.xyz/assets/prothom-feni.com.png",
        category: "otherLocalNewspapers",
        url: "prothom-feni.com",
    },
    {
        title: "Amar Noakhali",
        img: "https://www.allbanglanewspaper.xyz/assets/amarnoakhali.com.png",
        category: "otherLocalNewspapers",
        url: "amarnoakhali.com",
    },
    {
        title: "Andoloner Bazar",
        img: "https://www.allbanglanewspaper.xyz/assets/dailyandolonerbazar.com.png",
        category: "otherLocalNewspapers",
        url: "dailyandolonerbazar.com",
    },
    {
        title: "Mymensingh Pratidin",
        img: "https://www.allbanglanewspaper.xyz/assets/mymensinghpratidin.com.png",
        category: "otherLocalNewspapers",
        url: "mymensinghpratidin.com",
    },
    {
        title: "AFP",
        img: "https://www.allbanglanewspaper.xyz/assets/afp.com.jpg",
        category: "internationalNewspapers",
        url: "afp.com",
    },
    {
        title: "The Guardian",
        img: "https://www.allbanglanewspaper.xyz/assets/theguardian.com.jpg",
        category: "internationalNewspapers",
        url: "theguardian.com",
    },
    {
        title: "Abc News",
        img: "https://www.allbanglanewspaper.xyz/assets/abcnews.go.com.jpg",
        category: "internationalNewspapers",
        url: "abcnews.go.com",
    },
    {
        title: "Dailystar",
        img: "https://www.allbanglanewspaper.xyz/assets/thedailystar.net.jpg",
        category: "internationalNewspapers",
        url: "thedailystar.net",
    },
    {
        title: "Moscow Times",
        img: "https://www.allbanglanewspaper.xyz/assets/themoscowtimes.com.jpg",
        category: "internationalNewspapers",
        url: "themoscowtimes.com",
    },
    {
        title: "Independent",
        img: "https://www.allbanglanewspaper.xyz/assets/theindependentbd.com.jpg",
        category: "internationalNewspapers",
        url: "theindependentbd.com",
    },
    {
        title: "New Age",
        img: "https://www.allbanglanewspaper.xyz/assets/newagebd.net.jpg",
        category: "internationalNewspapers",
        url: "newagebd.net",
    },
    {
        title: "Yahoo News",
        img: "https://www.allbanglanewspaper.xyz/assets/news.yahoo.com.jpg",
        category: "internationalNewspapers",
        url: "news.yahoo.com",
    },
    {
        title: "Daily Sun",
        img: "https://www.allbanglanewspaper.xyz/assets/daily-sun.com.jpg",
        category: "internationalNewspapers",
        url: "daily-sun.com",
    },
    {
        title: "Bangladesh Today",
        img: "https://www.allbanglanewspaper.xyz/assets/thebangladeshtoday.com.jpg",
        category: "internationalNewspapers",
        url: "thebangladeshtoday.com",
    },
    {
        title: "News Today",
        img: "https://www.allbanglanewspaper.xyz/assets/newstoday.com.bd.jpg",
        category: "internationalNewspapers",
        url: "newstoday.com.bd",
    },
    {
        title: "Financial Express",
        img: "https://www.allbanglanewspaper.xyz/assets/thefinancialexpress-bd.com.jpg",
        category: "internationalNewspapers",
        url: "thefinancialexpress.com.bd",
    },
    {
        title: "Nytimes",
        img: "https://www.allbanglanewspaper.xyz/assets/nytimes.com.jpg",
        category: "internationalNewspapers",
        url: "nytimes.com",
    },
    {
        title: "Hindustan Times",
        img: "https://www.allbanglanewspaper.xyz/assets/hindustantimes.com.jpg",
        category: "internationalNewspapers",
        url: "hindustantimes.com",
    },

    {
        title: "CNN",
        img: "https://www.allbanglanewspaper.xyz/assets/edition.cnn.com.jpg",
        category: "internationalTVChannels",
        url: "edition.cnn.com",
    },
    {
        title: "Aljazeera",
        img: "https://www.allbanglanewspaper.xyz/assets/aljazeera.com.jpg",
        category: "internationalTVChannels",
        url: "aljazeera.com",
    },
    {
        title: "BBC",
        img: "https://www.allbanglanewspaper.xyz/assets/bbc.com.jpg",
        category: "internationalTVChannels",
        url: "bbc.com",
    },
    {
        title: "NDTV",
        img: "https://www.allbanglanewspaper.xyz/assets/ndtv.com.jpg",
        category: "internationalTVChannels",
        url: "ndtv.com",
    },
    {
        title: "Reuters",
        img: "https://www.allbanglanewspaper.xyz/assets/reuters.com.jpg",
        category: "internationalTVChannels",
        url: "reuters.com",
    },
    {
        title: "Foxnews",
        img: "https://www.allbanglanewspaper.xyz/assets/foxnews.com.jpg",
        category: "internationalTVChannels",
        url: "foxnews.com",
    },
    {
        title: "GEO",
        img: "https://www.allbanglanewspaper.xyz/assets/geo.tv.jpg",
        category: "internationalTVChannels",
        url: "geo.tv",
    },
    {
        title: "Sky News",
        img: "https://www.allbanglanewspaper.xyz/assets/news.sky.com.jpg",
        category: "internationalTVChannels",
        url: "news.sky.com",
    },
    {
        title: "Euronews",
        img: "https://www.allbanglanewspaper.xyz/assets/euronews.com.jpg",
        category: "internationalTVChannels",
        url: "euronews.com",
    },
    {
        title: "Press Tv",
        img: "https://www.allbanglanewspaper.xyz/assets/presstv.ir.jpg",
        category: "internationalTVChannels",
        url: "presstv.ir",
    },
    {
        title: "Discovery",
        img: "https://www.allbanglanewspaper.xyz/assets/discovery.com.jpg",
        category: "internationalTVChannels",
        url: "discovery.com",
    },
    {
        title: "CCTV",
        img: "https://www.allbanglanewspaper.xyz/assets/english.cntv.cn.jpg",
        category: "internationalTVChannels",
        url: "english.cntv.cn",
    },
    {
        title: "Ananda Bazar",
        img: "https://www.allbanglanewspaper.xyz/assets/anandabazar.com.jpg",
        category: "indianNewspapers",
        url: "anandabazar.com",
    },
    {
        title: "Aaj Kaal",
        img: "https://www.allbanglanewspaper.xyz/assets/aajkaal.net.jpg",
        category: "indianNewspapers",
        url: "aajkaal.net",
    },
    {
        title: "Kolkata24x7",
        img: "https://www.allbanglanewspaper.xyz/assets/kolkata24x7.com.png",
        category: "indianNewspapers",
        url: "kolkata24x7.com",
    },
    {
        title: "24 Ghanta",
        img: "https://www.allbanglanewspaper.xyz/assets/24ghanta.com.png",
        category: "indianNewspapers",
        url: "zeenews bengali",
    },
    {
        title: "ABP Ananda",
        img: "https://www.allbanglanewspaper.xyz/assets/abpananda.abplive.in.png",
        category: "indianNewspapers",
        url: "abpananda",
    },
    {
        title: "NDTV Bengali",
        img: "https://www.allbanglanewspaper.xyz/assets/ndtv-bangla.png",
        category: "indianNewspapers",
        url: "www.ndtv.com/bengali",
    },
    {
        title: "Syandan Patrika",
        img: "https://www.allbanglanewspaper.xyz/assets/syandanpatrika.com.jpg",
        category: "indianNewspapers",
        url: "syandanpatrika.com",
    },
    {
        title: "Sangbad Pratidin",
        img: "https://www.allbanglanewspaper.xyz/assets/sangbadpratidin.in.jpg",
        category: "indianNewspapers",
        url: "sangbadpratidin.in",
    },
    {
        title: "Bartaman Patrika",
        img: "https://www.allbanglanewspaper.xyz/assets/bartamanpatrika.com.jpg",
        category: "indianNewspapers",
        url: "bartamanpatrika.com",
    },
    {
        title: "Ganashakti",
        img: "https://www.allbanglanewspaper.xyz/assets/ganashakti.com.jpg",
        category: "indianNewspapers",
        url: "ganashakti.com",
    },
    {
        title: "Asomiya Pratidin",
        img: "https://www.allbanglanewspaper.xyz/assets/asomiyapratidin.co.in.jpg",
        category: "indianNewspapers",
        url: "asomiyapratidin.co.in",
    },
    {
        title: "Nababarta Prasanga",
        img: "https://www.allbanglanewspaper.xyz/assets/nababartaprasanga.com.jpg",
        category: "indianNewspapers",
        url: "nababartaprasanga.com",
    },
    {
        title: "Eisamay",
        img: "https://www.allbanglanewspaper.xyz/assets/epaper.eisamay.com.jpg",
        category: "indianNewspapers",
        url: "epaper.eisamay.com",
    },
    {
        title: "Uttarbanga Sambad",
        img: "https://www.allbanglanewspaper.xyz/assets/uttarbangasambad.com.jpg",
        category: "indianNewspapers",
        url: "uttarbangasambad.com",
    },
    {
        title: "Ebela",
        img: "https://www.allbanglanewspaper.xyz/assets/ebela.in.jpg",
        category: "indianNewspapers",
        url: "ebela.in",
    },
    {
        title: "Dainik Sambad",
        img: "https://www.allbanglanewspaper.xyz/assets/dainiksambad.net.jpg",
        category: "indianNewspapers",
        url: "dainiksambad.net",
    },
    {
        title: "Aamader Malda",
        img: "https://www.allbanglanewspaper.xyz/assets/aamadermalda.in.png",
        category: "indianNewspapers",
        url: "aamadermalda.in",
    },
    {
        title: "Ganashakti",
        img: "https://www.allbanglanewspaper.xyz/assets/bangla.ganashakti.co.in.png",
        category: "indianNewspapers",
        url: "bangla.ganashakti.co.in",
    },
    {
        title: "Arthosuchak",
        img: "https://www.allbanglanewspaper.xyz/assets/arthosuchak.png",
        category: "sharebazarNewspapers",
        url: "arthosuchak.com",
    },
    {
        title: "Sharenews24",
        img: "https://www.allbanglanewspaper.xyz/assets/sharenews24.jpg",
        category: "sharebazarNewspapers",
        url: "sharenews24.com",
    },
    {
        title: "Sunbd24",
        img: "https://www.allbanglanewspaper.xyz/assets/sunbd24.png",
        category: "sharebazarNewspapers",
        url: "sunbd24.com",
    },
    {
        title: "sharebazarnews",
        img: "https://www.allbanglanewspaper.xyz/assets/sharebazarnews.png",
        category: "sharebazarNewspapers",
        url: "sharebazarnews.com",
    },
    {
        title: "Daily Bonikbarta",
        img: "https://www.allbanglanewspaper.xyz/assets/bonikbarta.com.jpg",
        category: "sharebazarNewspapers",
        url: "bonikbarta.net",
    },
    {
        title: "Share Biz",
        img: "https://www.allbanglanewspaper.xyz/assets/sharebiz.net.jpg",
        category: "sharebazarNewspapers",
        url: "sharebiz.net",
    },
    {
        title: "Stockbangladesh",
        img: "https://www.allbanglanewspaper.xyz/assets/stock-bangladesh.png",
        category: "sharebazarNewspapers",
        url: "dailystockbangladesh.com",
    },
    {
        title: "Financial Express",
        img: "https://www.allbanglanewspaper.xyz/assets/thefinancialexpress-bd.com.jpg",
        category: "sharebazarNewspapers",
        url: "thefinancialexpress.com.bd",
    },
    {
        title: "Ajkerbazar",
        img: "https://www.allbanglanewspaper.xyz/assets/ajkerbazzar.png",
        category: "sharebazarNewspapers",
        url: "ajkerbazzar.com",
    },
    {
        title: "Ortho Songbad",
        img: "https://www.allbanglanewspaper.xyz/assets/orthosongbad.jpg",
        category: "sharebazarNewspapers",
        url: "orthosongbad.com",
    },
    {
        title: "Businesshour24",
        img: "https://www.allbanglanewspaper.xyz/assets/businesshour.png",
        category: "sharebazarNewspapers",
        url: "businesshour24.com",
    },
    {
        title: "Corporate Sangbad",
        img: "https://www.allbanglanewspaper.xyz/assets/corporatesangbad.png",
        category: "sharebazarNewspapers",
        url: "corporatesangbad.com",
    },
    {
        title: "Business Eye BD",
        img: "https://www.allbanglanewspaper.xyz/assets/business-eye-bd.jpg",
        category: "sharebazarNewspapers",
        url: "businesseyebd.com",
    },
    {
        title: "Pujibazar",
        img: "https://www.allbanglanewspaper.xyz/assets/pujibazar.png",
        category: "sharebazarNewspapers",
        url: "pujibazar.com",
    },
    {
        title: "Share Bazar Protidin",
        img: "https://www.allbanglanewspaper.xyz/assets/dailysharebazarprotidin.png",
        category: "sharebazarNewspapers",
        url: "dailysharebazarprotidin.com",
    },
    {
        title: "Desh Protikhon",
        img: "https://www.allbanglanewspaper.xyz/assets/deshprotikhon.png",
        category: "sharebazarNewspapers",
        url: "deshprotikhon.com",
    },
    {
        title: "Arthoniteer Kagoj",
        img: "https://www.allbanglanewspaper.xyz/assets/arthoniteerkagoj.png",
        category: "sharebazarNewspapers",
        url: "arthoniteerkagoj.com",
    },
    {
        title: "Sharebusiness24",
        img: "https://www.allbanglanewspaper.xyz/assets/sharebusiness24.jpg",
        category: "sharebazarNewspapers",
        url: "sharebusiness24.com",
    },
    {
        title: "Biniogbarta",
        img: "https://www.allbanglanewspaper.xyz/assets/biniogbarta.png",
        category: "sharebazarNewspapers",
        url: "biniogbarta.com",
    },
    {
        title: "Energy Bangla",
        img: "https://www.allbanglanewspaper.xyz/assets/energy-bangla-news.jpg",
        category: "sharebazarNewspapers",
        url: "energybangla.com.bd",
    },
    {
        title: "Sharebarta24",
        img: "https://www.allbanglanewspaper.xyz/assets/share-barta-24-newspaper.png",
        category: "sharebazarNewspapers",
        url: "sharebarta24.com",
    },
    {
        title: "Business News24bd",
        img: "https://www.allbanglanewspaper.xyz/assets/businessnews24bd.jpg",
        category: "sharebazarNewspapers",
        url: "businessnews24bd.com",
    },
    {
        title: "Biniyoug Barta",
        img: "https://www.allbanglanewspaper.xyz/assets/biniyougbarta.png",
        category: "sharebazarNewspapers",
        url: "biniyougbarta.com",
    },
    {
        title: "Bdcap24.net",
        img: "https://www.allbanglanewspaper.xyz/assets/bdcap24.net.png",
        category: "sharebazarNewspapers",
        url: "bdcap24.net",
    },
    {
        title: "Insurance News Bd",
        img: "https://www.allbanglanewspaper.xyz/assets/insurancenewsbd.png",
        category: "sharebazarNewspapers",
        url: "insurancenewsbd.com",
    },
    {
        title: "Insurance Bd",
        img: "https://www.allbanglanewspaper.xyz/assets/insurancebd.png",
        category: "sharebazarNewspapers",
        url: "insurancebd.news",
    },
    {
        title: "Bank Bima Arthonity",
        img: "https://www.allbanglanewspaper.xyz/assets/bankbimaarthonity.png",
        category: "sharebazarNewspapers",
        url: "bankbimaarthonity.com",
    },
    {
        title: "Banking News Bd",
        img: "https://www.allbanglanewspaper.xyz/assets/bankingnewsbd.png",
        category: "sharebazarNewspapers",
        url: "bankingnewsbd.com",
    },
    {
        title: "Business News Bd",
        img: "https://www.allbanglanewspaper.xyz/assets/bbn.png",
        category: "sharebazarNewspapers",
        url: "businessnews-bd.net",
    },

    {
        title: "Dhaka Stock Exchange",
        img: "https://www.allbanglanewspaper.xyz/assets/dse.jpg",
        category: "stockExchange",
        url: "www.dsebd.org",
    },
    {
        title: "Chittagong Stock Exchange",
        img: "https://www.allbanglanewspaper.xyz/assets/cse-logo.jpg",
        category: "stockExchange",
        url: "www.cse.com.bd",
    },
    {
        title: 'Bangladesh Bank',
        img: 'https://www.allbanglanewspaper.xyz/assets/bangladesh-bank.jpg',
        category: 'otherUsefulLinks',
        url: 'https://bb.org.bd/'
    },
    {
        title: 'CDDBL',
        img: 'https://www.allbanglanewspaper.xyz/assets/cdbl.jpg',
        category: 'otherUsefulLinks',
        url: 'https://cdbl.com.bd/'
    },
    {
        title: 'Stock Bangladesh',
        img: 'https://www.allbanglanewspaper.xyz/assets/stockbangladesh.jpg',
        category: 'otherUsefulLinks',
        url: 'https://stockbangladesh.com/'
    },
    {
        title: 'Amar Stock',
        img: 'https://www.allbanglanewspaper.xyz/assets/amarstock.jpg',
        category: 'otherUsefulLinks',
        url: 'https://www.amarstock.com/'
    },
    {
        title: 'Lanka Bangla Finance',
        img: 'https://www.allbanglanewspaper.xyz/assets/lankabanglafinance.jpg',
        category: 'otherUsefulLinks',
        url: 'https://lankabd.com/'
    },
    {
        title: 'BIASL',
        img: 'https://www.allbanglanewspaper.xyz/assets/biasl.jpg',
        category: 'otherUsefulLinks',
        url: 'https://biasl.net/'
    },
    {
        title: 'BRAC EPL',
        img: 'https://www.allbanglanewspaper.xyz/assets/brac-epl.jpg',
        category: 'otherUsefulLinks',
        url: 'https://bracepl.com/'
    },
    {
        title: 'EBL',
        img: 'https://www.allbanglanewspaper.xyz/assets/ebl.jpg',
        category: 'otherUsefulLinks',
        url: 'https://www.eblsecurities.com/'
    },
    {
        title: 'Sheltech',
        img: 'https://www.allbanglanewspaper.xyz/assets/sheltech.jpg',
        category: 'otherUsefulLinks',
        url: 'https://sheltechbrokerage.com/'
    },
    {
        title: 'City Brokarage',
        img: 'https://www.allbanglanewspaper.xyz/assets/citybrokarage.jpg',
        category: 'otherUsefulLinks',
        url: 'https://citybrokerageltd.com/'
    },
    {
        title: 'Bbusiness Insider',
        img: 'https://www.allbanglanewspaper.xyz/assets/businessinsider.jpg',
        category: 'otherUsefulLinks',
        url: 'https://www.businessinsider.com/'
    },
    {
        title: 'Economist',
        img: 'https://www.allbanglanewspaper.xyz/assets/economist.jpg',
        category: 'otherUsefulLinks',
        url: 'https://www.economist.com/'
    },
    {
        title: 'Bloomberg',
        img: 'https://www.allbanglanewspaper.xyz/assets/bloomberg.jpg',
        category: 'otherUsefulLinks',
        url: 'https://www.bloomberg.com/'
    }
]